# n8n-docker-compose-exemplos-ptbr
#   - n8n-sqlite docker compose
# Refatorado para usar volumes nomeados (melhor persistencia)
services:
  n8n:
    image: n8nio/n8n:${N8N_VERSION:-latest}
    container_name: n8n
    restart: unless-stopped
    # Se quiser esconder o n8n e expor atrávez de proxy, comente ou remova a sessão ports
    ports:
      - "${BIND_IP:-0.0.0.0}:${BIND_PORT:-5678}:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n

# Se quiser esconder o n8n e expor atrávez de proxy, descomente a sessão networks e coloque na mesma rede do seu proxy
# Obs: A rede deve existir previamente
#    networks:
#      - n8n-proxy


#networks:
#  n8n-proxy:
#    name: n8n-proxy
#    driver: bridge
#    external: true

volumes:
  n8n_data: